/* ============================================================
   search.js — site search for the study notes.

   Drop <script src="search.js" defer></script> into any page and it
   builds its own UI, styles and behaviour. Nothing else on the page
   needs to know about it.

   Two scopes:
     This page — walks the live DOM, highlights every match, and steps
                 through them. Works on content generated by JavaScript,
                 and opens any <details> or collapsed panel it lands in.
     All pages — looks up search-index.js, which is generated from the
                 site's text and loaded the first time it is needed.

   Deep links: results link to  page.html?find=<query>#<section>, and the
   script picks that up on arrival to re-run the in-page highlight.
   ============================================================ */
(function () {
  "use strict";

  var INDEX_FILE = "search-index.js";
  var MAX_RESULTS = 40;
  var SNIPPET_PAD = 90;

  /* ---------- styles ---------- */
  var CSS = [
    /* standalone pages: the bar pins itself */
    '.sr-wrap{position:sticky;top:0;z-index:60;background:#fff;border-bottom:1px solid #dde3e7;padding:8px 20px}',
    '@media(max-width:700px){.sr-wrap{padding:8px 14px}}',
    /* pages with a topbar: sit inside it, so the two pin as one block */
    '.topbar .sr-wrap{position:static;background:none;border-bottom:0;padding:0 0 10px}',
    '.topbar .sr-row{max-width:none}',
    '.topbar .sr-panel{max-width:none}',
    '.sr-row{display:flex;gap:8px;align-items:center;max-width:1180px;margin:0 auto;flex-wrap:wrap}',
    '.sr-field{position:relative;flex:1 1 220px;min-width:0;display:flex;align-items:center}',
    '.sr-field svg{position:absolute;left:9px;width:14px;height:14px;opacity:.45;pointer-events:none}',
    '.sr-input{width:100%;font:inherit;font-size:.92rem;padding:7px 30px 7px 28px;border:1px solid #cfd6da;border-radius:4px;background:#fbfcfc;color:#131b26}',
    '.sr-input::-webkit-search-cancel-button,.sr-input::-webkit-search-decoration{-webkit-appearance:none;appearance:none}',
    '.sr-input:focus{outline:none;border-color:#1f6b6b;background:#fff;box-shadow:0 0 0 2px rgba(31,107,107,.14)}',
    '.sr-clear{position:absolute;right:4px;border:0;background:none;font-size:1.05rem;line-height:1;color:#8b959b;cursor:pointer;padding:3px 6px}',
    '.sr-clear:hover{color:#131b26}',
    '.sr-scope{display:flex;border:1px solid #cfd6da;border-radius:4px;overflow:hidden;flex:0 0 auto}',
    '.sr-scope button{font:inherit;font-size:.78rem;font-weight:600;padding:7px 10px;border:0;background:#fbfcfc;color:#5a656c;cursor:pointer;white-space:nowrap}',
    '.sr-scope button+button{border-left:1px solid #cfd6da}',
    '.sr-scope button[aria-pressed="true"]{background:#1f6b6b;color:#fff}',
    '.sr-nav{display:flex;align-items:center;gap:6px;flex:0 0 auto;font-size:.8rem;color:#5a656c}',
    '.sr-nav button{font:inherit;border:1px solid #cfd6da;background:#fbfcfc;border-radius:4px;padding:5px 9px;cursor:pointer;color:#131b26;line-height:1}',
    '.sr-nav button:disabled{opacity:.4;cursor:default}',
    '.sr-count{min-width:76px;font-variant-numeric:tabular-nums}',
    '.sr-panel{max-width:1180px;margin:8px auto 0;border:1px solid #dde3e7;border-radius:4px;background:#fff;max-height:60vh;overflow:auto;display:none}',
    '.sr-panel.open{display:block}',
    '.sr-note{padding:12px 14px;font-size:.86rem;color:#5a656c}',
    '.sr-group{border-top:1px solid #eef2f4}',
    '.sr-group:first-child{border-top:0}',
    '.sr-gh{font-size:.72rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#1f6b6b;padding:9px 14px 3px}',
    '.sr-hit{display:block;padding:7px 14px 9px;border-top:1px solid #f2f5f6;text-decoration:none;color:inherit}',
    '.sr-hit:first-of-type{border-top:0}',
    '.sr-hit:hover,.sr-hit:focus{background:#f3f7f7;outline:none}',
    '.sr-hit b{display:block;font-size:.85rem;font-weight:600;color:#131b26;margin-bottom:2px}',
    '.sr-hit span{display:block;font-size:.8rem;color:#5a656c;line-height:1.45}',
    '.sr-hit em{font-style:normal;background:#ffe9a8;color:#3a2f00;border-radius:2px;padding:0 1px}',
    'mark.sr-mark{background:#ffe9a8;color:inherit;border-radius:2px;padding:0 1px}',
    'mark.sr-mark.sr-current{background:#f7a23b;color:#1b1200}'
  ].join("\n");

  /* ---------- helpers ---------- */
  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html != null) n.innerHTML = html;
    return n;
  }
  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }
  function norm(s) { return String(s).toLowerCase(); }
  function terms(q) {
    return norm(q).split(/\s+/).filter(function (t) { return t.length > 1; });
  }

  /* ============================================================
     IN-PAGE SEARCH
     ============================================================ */
  var marks = [];
  var cursor = -1;

  var SKIP = /^(script|style|noscript|textarea|mark|svg)$/i;

  function clearMarks() {
    marks.forEach(function (m) {
      var p = m.parentNode;
      if (!p) return;
      p.replaceChild(document.createTextNode(m.textContent), m);
      p.normalize();
    });
    marks = [];
    cursor = -1;
  }

  function markPage(query) {
    clearMarks();
    var q = query.trim();
    if (q.length < 2) { updateNav(); return; }
    var needle = norm(q);

    var root = document.querySelector(".wrap") || document.body;
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: function (node) {
        if (!node.nodeValue || !node.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
        var p = node.parentNode;
        while (p && p !== root) {
          if (SKIP.test(p.nodeName)) return NodeFilter.FILTER_REJECT;
          if (p.classList && (p.classList.contains("sr-wrap") || p.classList.contains("sr-panel"))) {
            return NodeFilter.FILTER_REJECT;
          }
          p = p.parentNode;
        }
        return norm(node.nodeValue).indexOf(needle) === -1
          ? NodeFilter.FILTER_REJECT
          : NodeFilter.FILTER_ACCEPT;
      }
    });

    var targets = [], n;
    while ((n = walker.nextNode())) targets.push(n);

    targets.forEach(function (node) {
      var text = node.nodeValue, low = norm(text), out = [], at = 0, i;
      while ((i = low.indexOf(needle, at)) !== -1) {
        if (i > at) out.push(document.createTextNode(text.slice(at, i)));
        var m = el("mark", "sr-mark");
        m.textContent = text.slice(i, i + needle.length);
        out.push(m);
        marks.push(m);
        at = i + needle.length;
      }
      if (!out.length) return;
      if (at < text.length) out.push(document.createTextNode(text.slice(at)));
      var frag = document.createDocumentFragment();
      out.forEach(function (x) { frag.appendChild(x); });
      node.parentNode.replaceChild(frag, node);
    });

    updateNav();
  }

  /* open anything collapsed that a match is hiding inside */
  function reveal(node) {
    var p = node.parentNode;
    while (p && p !== document.body) {
      if (p.nodeName === "DETAILS") p.open = true;
      if (p.getAttribute && p.getAttribute("open-state") === "closed") {
        p.setAttribute("open-state", "open");
        var head = p.querySelector('[aria-expanded="false"]');
        if (head) head.setAttribute("aria-expanded", "true");
      }
      p = p.parentNode;
    }
  }

  function goTo(i) {
    if (!marks.length) return;
    cursor = (i + marks.length) % marks.length;
    marks.forEach(function (m) { m.classList.remove("sr-current"); });
    var m = marks[cursor];
    m.classList.add("sr-current");
    reveal(m);
    m.scrollIntoView({ behavior: "smooth", block: "center" });
    updateNav();
  }

  /* ============================================================
     SITE-WIDE SEARCH
     ============================================================ */
  var indexState = "idle"; // idle | loading | ready | failed

  function loadIndex(cb) {
    if (indexState === "ready") return cb(true);
    if (indexState === "failed") return cb(false);
    if (indexState === "loading") return;
    indexState = "loading";
    var s = document.createElement("script");
    s.src = INDEX_FILE;
    s.onload = function () {
      indexState = window.SEARCH_INDEX ? "ready" : "failed";
      cb(indexState === "ready");
    };
    s.onerror = function () { indexState = "failed"; cb(false); };
    document.head.appendChild(s);
  }

  function searchIndex(query) {
    var ts = terms(query);
    if (!ts.length) return [];
    var out = [];
    (window.SEARCH_INDEX.pages || []).forEach(function (page) {
      (page.s || []).forEach(function (sec) {
        var low = norm(sec.t), score = 0, ok = true;
        ts.forEach(function (t) {
          var c = 0, at = 0, i;
          while ((i = low.indexOf(t, at)) !== -1) { c++; at = i + t.length; }
          if (!c) ok = false;
          score += c;
        });
        if (!ok) return;
        if (norm(sec.h).indexOf(ts[0]) !== -1) score += 12;
        if (norm(page.t).indexOf(ts[0]) !== -1) score += 6;
        out.push({ page: page, sec: sec, score: score, low: low });
      });
    });
    out.sort(function (a, b) { return b.score - a.score; });
    return out.slice(0, MAX_RESULTS);
  }

  function snippet(text, low, ts) {
    var i = low.indexOf(ts[0]);
    if (i === -1) i = 0;
    var from = Math.max(0, i - SNIPPET_PAD);
    var to = Math.min(text.length, i + ts[0].length + SNIPPET_PAD);
    var cut = text.slice(from, to);
    var html = esc(cut);
    ts.forEach(function (t) {
      html = html.replace(new RegExp("(" + t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + ")", "gi"), "<em>$1</em>");
    });
    return (from > 0 ? "\u2026" : "") + html + (to < text.length ? "\u2026" : "");
  }

  /* ============================================================
     UI
     ============================================================ */
  var scope = "page";
  var input, panel, countEl, prevBtn, nextBtn, scopeBtns = {};

  function updateNav() {
    if (scope !== "page") {
      countEl.textContent = "";
      prevBtn.disabled = nextBtn.disabled = true;
      return;
    }
    var q = input.value.trim();
    if (q.length < 2) { countEl.textContent = ""; }
    else if (!marks.length) { countEl.textContent = "no matches"; }
    else { countEl.textContent = (cursor < 0 ? 1 : cursor + 1) + " of " + marks.length; }
    prevBtn.disabled = nextBtn.disabled = marks.length === 0;
  }

  function renderResults(query) {
    var ts = terms(query);
    if (!ts.length) { panel.classList.remove("open"); return; }
    var hits = searchIndex(query);
    panel.innerHTML = "";
    if (!hits.length) {
      panel.appendChild(el("p", "sr-note", "No matches for &ldquo;" + esc(query) + "&rdquo; anywhere on the site."));
      panel.classList.add("open");
      return;
    }
    var byPage = {};
    hits.forEach(function (h) {
      (byPage[h.page.f] = byPage[h.page.f] || { page: h.page, hits: [] }).hits.push(h);
    });
    Object.keys(byPage).forEach(function (f) {
      var g = byPage[f];
      var group = el("div", "sr-group");
      group.appendChild(el("p", "sr-gh", esc(g.page.t)));
      g.hits.forEach(function (h) {
        var href = g.page.f + "?find=" + encodeURIComponent(query) + (h.sec.id ? "#" + h.sec.id : "");
        var a = el("a", "sr-hit");
        a.href = href;
        a.innerHTML = "<b>" + esc(h.sec.h || g.page.t) + "</b><span>" + snippet(h.sec.t, h.low, ts) + "</span>";
        group.appendChild(a);
      });
      panel.appendChild(group);
    });
    panel.classList.add("open");
  }

  function run() {
    var q = input.value;
    if (scope === "page") {
      panel.classList.remove("open");
      markPage(q);
      if (marks.length) goTo(0);
    } else {
      clearMarks();
      updateNav();
      if (q.trim().length < 2) { panel.classList.remove("open"); return; }
      panel.innerHTML = "";
      panel.appendChild(el("p", "sr-note", "Loading the site index\u2026"));
      panel.classList.add("open");
      loadIndex(function (ok) {
        if (!ok) {
          panel.innerHTML = "";
          panel.appendChild(el("p", "sr-note",
            "Could not load <code>" + INDEX_FILE + "</code>, so only this page can be searched. " +
            "The file needs to sit alongside the pages."));
          return;
        }
        renderResults(q);
      });
    }
  }

  function setScope(next) {
    scope = next;
    scopeBtns.page.setAttribute("aria-pressed", String(next === "page"));
    scopeBtns.site.setAttribute("aria-pressed", String(next === "site"));
    run();
  }

  function build() {
    document.head.appendChild(el("style", null, CSS));

    var wrap = el("div", "sr-wrap");
    var row = el("div", "sr-row");

    var field = el("div", "sr-field");
    field.innerHTML =
      '<svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="7" cy="7" r="5" fill="none" stroke="currentColor" stroke-width="2"/>' +
      '<path d="M11 11l4 4" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>';
    input = el("input", "sr-input");
    input.type = "search";
    input.placeholder = "Search \u2014 press / to focus";
    input.setAttribute("aria-label", "Search the study notes");
    field.appendChild(input);
    var clearBtn = el("button", "sr-clear", "&times;");
    clearBtn.type = "button";
    clearBtn.setAttribute("aria-label", "Clear search");
    field.appendChild(clearBtn);
    row.appendChild(field);

    var sc = el("div", "sr-scope");
    scopeBtns.page = el("button", null, "This page");
    scopeBtns.site = el("button", null, "All pages");
    scopeBtns.page.type = scopeBtns.site.type = "button";
    scopeBtns.page.setAttribute("aria-pressed", "true");
    scopeBtns.site.setAttribute("aria-pressed", "false");
    sc.appendChild(scopeBtns.page);
    sc.appendChild(scopeBtns.site);
    row.appendChild(sc);

    var nav = el("div", "sr-nav");
    prevBtn = el("button", null, "\u2191");
    nextBtn = el("button", null, "\u2193");
    prevBtn.type = nextBtn.type = "button";
    prevBtn.setAttribute("aria-label", "Previous match");
    nextBtn.setAttribute("aria-label", "Next match");
    countEl = el("span", "sr-count");
    nav.appendChild(prevBtn);
    nav.appendChild(nextBtn);
    nav.appendChild(countEl);
    row.appendChild(nav);

    wrap.appendChild(row);
    panel = el("div", "sr-panel");
    wrap.appendChild(panel);

    /* Inside the topbar where there is one: it is already position:sticky,
       and two sticky elements both pinned to top:0 would overlap. On pages
       with no topbar the bar pins itself instead. */
    var host = document.querySelector(".wrap") || document.body;
    var bar = host.querySelector(".topbar");
    if (bar) bar.appendChild(wrap);
    else host.insertBefore(wrap, host.firstChild);

    /* events */
    var t;
    input.addEventListener("input", function () {
      clearTimeout(t);
      t = setTimeout(run, scope === "page" ? 160 : 220);
    });
    input.addEventListener("keydown", function (e) {
      if (e.key === "Enter") { e.preventDefault(); if (scope === "page") goTo(cursor + (e.shiftKey ? -1 : 1)); }
      if (e.key === "Escape") { input.value = ""; clearMarks(); panel.classList.remove("open"); updateNav(); input.blur(); }
    });
    clearBtn.addEventListener("click", function () {
      input.value = ""; clearMarks(); panel.classList.remove("open"); updateNav(); input.focus();
    });
    prevBtn.addEventListener("click", function () { goTo(cursor - 1); });
    nextBtn.addEventListener("click", function () { goTo(cursor + 1); });
    scopeBtns.page.addEventListener("click", function () { setScope("page"); });
    scopeBtns.site.addEventListener("click", function () { setScope("site"); });

    document.addEventListener("keydown", function (e) {
      var typing = /^(input|textarea|select)$/i.test(e.target.nodeName);
      if (!typing && e.key === "/") { e.preventDefault(); input.focus(); input.select(); }
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") { e.preventDefault(); input.focus(); input.select(); }
    });
    document.addEventListener("click", function (e) {
      if (!wrap.contains(e.target)) panel.classList.remove("open");
    });

    /* arriving from a site-wide result */
    var found = new URLSearchParams(location.search).get("find");
    if (found) {
      input.value = found;
      setTimeout(function () {
        markPage(found);
        var anchor = location.hash ? document.querySelector(location.hash) : null;
        var start = 0;
        if (anchor) {
          for (var i = 0; i < marks.length; i++) {
            if (anchor.contains(marks[i])) { start = i; break; }
          }
        }
        if (marks.length) goTo(start);
      }, 350); /* let JS-built pages finish rendering */
    }

    updateNav();
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", build);
  else build();
})();
